#!/usr/bin/env bash
# Existing recovery section claims "Branch: stale-branch" but hook runs in
# a real git repo where current branch differs. Recovery should reflect
# current state, not stale.
PROJ="$TEST_DIR/project"
mkdir -p "$PROJ"
cd "$PROJ" || exit 1
rm -rf .git CLAUDE.md *.txt 2>/dev/null
git init -q -b actual-current-branch
git config user.email "test@example.com"
git config user.name "Test"
echo "content" > foo.txt
git add foo.txt
git commit -q -m "Real commit message"
cat > CLAUDE.md <<'EOF'
# Test

<!-- post-compact-recovery-start -->
## Session Recovery (auto-generated by context-recovery hook)

**Branch:** stale-branch
**Recent commits:**
- old1234 Stale commit 1
- old5678 Stale commit 2

**Hook generated:** 2025-12-31 23:59:59 UTC
<!-- post-compact-recovery-end -->
EOF
