#!/usr/bin/env bash
# CLAUDE.md already has a recovery section from a previous PreCompact.
# Hook should replace it, not append a second one.
PROJ="$TEST_DIR/project"
mkdir -p "$PROJ"
cd "$PROJ" || exit 1
rm -rf .git CLAUDE.md 2>/dev/null
cat > CLAUDE.md <<'EOF'
# Test Project

Original project content.

<!-- post-compact-recovery-start -->
## Session Recovery (auto-generated by context-recovery hook)

**Branch:** old-branch
**Hook generated:** 2026-01-01 00:00:00 UTC
<!-- post-compact-recovery-end -->

More content after the recovery section.
EOF
